### ISSUE TITLE
EPIC Generate a report of values for all shares held

### ISSUE THREAD

**Issue by andyblight** [andyblight/share-tracking-1#7]
Updating the stop/loss for all shares I hold is something that I do every week, so this could help speed up the process. I also want to see which shares are making me money and the shares that are tailing off.

- [ ] Download EOD Data for the previous week.
- [ ] Import the data into the app.
- [ ] Using the latest Friday prices, generate a report of held shares showing: Share ticker, name, number held, price paid, latest price, profit, new stop/loss.

### Prerequisites

- [ ] Import securities list from EOD Data file. 
- [ ] Import transactions for shares.
- [ ] Produce holdings table from transactions.

**Comment by andyblight** [comment]
Reviewed work so far and updated this epic.
Split out design notes from README.
1h00
